### PR TITLE
Fix update uploader

### PR DESCRIPTION
**Pull request by thomasrockhu**

### CODE REVIEW

**Comment by richelbilderbeek** [comment]
@thomasrockhu I am sorry I missed this Pull Request, I even did not reply to a friendly contributor! I assume the PR is obsolete now?

**Comment by thomasrockhu** [comment]
@richelbilderbeek no worries! This was actually meant for the Codecov fork (and I haven't gotten it to work yet)

**Comment by richelbilderbeek** [comment]
Phew, I thought so! This repo does not work anymore since Travis went commercial :-/

**Comment by thomasrockhu** [comment]
@richelbilderbeek I'll likely try to get this working on GitHub Actions, but I'm not a cpp programmer. Happy to make a PR into this repo afterwards (although I guess the repo name would need to change?)

**Comment by richelbilderbeek** [comment]
Hi @thomasrockhu, I also make the switch to GitHub Actions and have repos for that. This repo -as you say rightfully so- has `travis` in the name and hence will remain on Travis :-)

**Pull request closed without merging**
